DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='admin') THEN
    CREATE ROLE admin LOGIN PASSWORD 'admin';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='app') THEN
    CREATE ROLE app LOGIN PASSWORD 'app';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='readonly') THEN
    CREATE ROLE readonly LOGIN PASSWORD 'readonly';
  END IF;
END$$;

GRANT USAGE ON SCHEMA service TO app, readonly;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA service TO app;
GRANT SELECT ON ALL TABLES IN SCHEMA service TO readonly;

GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA service TO app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA service TO readonly;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA service
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA service
  GRANT SELECT ON TABLES TO readonly;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA service
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO app;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA service
  GRANT USAGE, SELECT ON SEQUENCES TO readonly;
